setRefClass("PropertyWidget", contains = "Widget")
setRefClass("PropertySetWidget", contains = c("PropertySet", "PropertyWidget"))
setRefClass("ColorWidget", contains = c("Color", "PropertyWidget"))
setRefClass("ColorEnumWidget", contains = c("ColorEnum", "PropertyWidget"))
setRefClass("GlyphEnumWidget", contains = c("GlyphEnum", "PropertyWidget"))
setRefClass("SingleEnumWidget", contains = c("SingleEnum", "PropertyWidget"))
setRefClass("MultilpleEnumWidget", contains = c("MultipleEnum", "PropertyWidget"))
setRefClass("PositiveIntegerWidget", contains = c("PositiveInteger", "PropertyWidget"))
setRefClass("NegativeIntegerWidget", contains = c("NegativeInteger", "PropertyWidget"))
setRefClass("NonpositiveIntegerWidget", contains = c("NonpositiveInteger", "PropertyWidget"))
setRefClass("NonnegativeIntegerWidget", contains = c("NonnegativeInteger", "PropertyWidget"))
setRefClass("NumericWithRangeWidget", contains = c("NumericWithRange", "PropertyWidget"))
## setRefClass("IntegerWithRangeWidget", contains = c("IntegerWithRange", "PropertyWidget"))
setRefClass("NumericWithMin0Max1Widget", contains = c("NumericWithMin0Max1", "PropertyWidget"))

